server:
  port: 8088
  error:
    include-message: always
  servlet:
    context-path: /marvel
    
    
spring:
  application:
    name: marvel
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      
      
marvel:
  url-base: https://gateway.marvel.com:443/v1/public/characters
  apikey: 831197e178cd630551c03e6b9b8e1c65
  hash: d0153cecda67869bf2b554fe2dd18b63
  ts: 1